apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'maven-publish'

android {
    compileSdkVersion 29


    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 29
        versionCode 210200
        versionName "21.02.00"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        profile {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

//    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    testImplementation 'junit:junit:4.13'
}
repositories {
    mavenCentral()
}


publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.teskalabs.seacat'
            artifactId = 'seacat-android-g3'
            version = '21.2.0'
        }
    }
}
